//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.17 at 07:11:34 PM UTC 
//


package fr.univrouen.cv24.model.parser;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.univrouen.cv24.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cv24_QNAME = new QName("http://univ.fr/cv24", "cv24");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.univrouen.cv24.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cv24Type }
     * 
     */
    public Cv24Type createCv24Type() {
        return new Cv24Type();
    }

    /**
     * Create an instance of {@link IdentiteType }
     * 
     */
    public IdentiteType createIdentiteType() {
        return new IdentiteType();
    }

    /**
     * Create an instance of {@link ObjType }
     * 
     */
    public ObjType createObjType() {
        return new ObjType();
    }

    /**
     * Create an instance of {@link ProfType }
     * 
     */
    public ProfType createProfType() {
        return new ProfType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link CompType }
     * 
     */
    public CompType createCompType() {
        return new CompType();
    }

    /**
     * Create an instance of {@link DipType }
     * 
     */
    public DipType createDipType() {
        return new DipType();
    }

    /**
     * Create an instance of {@link CertifType }
     * 
     */
    public CertifType createCertifType() {
        return new CertifType();
    }

    /**
     * Create an instance of {@link DiversType }
     * 
     */
    public DiversType createDiversType() {
        return new DiversType();
    }

    /**
     * Create an instance of {@link LvType }
     * 
     */
    public LvType createLvType() {
        return new LvType();
    }

    /**
     * Create an instance of {@link AutreType }
     * 
     */
    public AutreType createAutreType() {
        return new AutreType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cv24Type }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Cv24Type }{@code >}
     */
    @XmlElementDecl(namespace = "http://univ.fr/cv24", name = "cv24")
    public JAXBElement<Cv24Type> createCv24(Cv24Type value) {
        return new JAXBElement<Cv24Type>(_Cv24_QNAME, Cv24Type.class, null, value);
    }

}
