//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.17 at 07:11:34 PM UTC 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://univ.fr/cv24", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.univrouen.cv24.model.parser;
